services:
  model_backend:
    build: ./model_backend
    container_name: mnist-model-backend
    depends_on:
      - mnist-db
    networks:
      - mnist_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      retries: 5

  web_app:
    build: ./web_app
    container_name: mnist-web-app
    ports:
      - "8501:8501"
    depends_on:
      - model_backend
    networks:
      - mnist_network

  mnist-db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mnist
      POSTGRES_PASSWORD: mnist
      POSTGRES_DB: mnist
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mnist_network

networks:
  mnist_network:

volumes:
  pgdata:
